spring:
  application:
    name: podo-user-service

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:9761/eureka/
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"
  cloud:
    config:
      name: podo
      profile: user

encrypt:
  key: ${ENCRYPT_KEY}