version: "3"
services:
  podobank:
    image: bangjinseong/podobank:${BUILD_NUMBER}
    build:
      context: ../Podo_Bank/backend
      dockerfile: Dockerfile.Podo_back
      args:
        - BUILD_NUMBER
    ports:
      - "9000:9000"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: bangjinseong/redis:${BUILD_NUMBER}
    ports:
      - "9050:6379"
    volumes:
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  #redis_dotori:
    #image: redis_dotori:{BUILD_NUMBER_DOTORI}
    #ports:
      # -"9150:6379"
    #volumes:
      # - /etc/redis/redis_dotori.conf