server:
  port: 9110
# http://j9d107.p.ssafy.io:9900/
spring:
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"
  cloud:
    config:
      name: dotori
      profile: auth
  application:
    name: dotori-auth-service

encrypt:
  key: ${ENCRYPT_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:8761/eureka
  instance:
    hostname: j9d107.p.ssafy.io


